all:
	gcc -o initramfs/xploit1 x1.c --static -masm=intel
	gcc -o initramfs/xploit2 x2.c --static -masm=intel
	gcc -o initramfs/xploit3 x3.c --static -masm=intel
	gcc -o initramfs/xploit4 x4.c --static -masm=intel

clean:
	rm xploit1
	rm xploit2
	rm xploit3
	rm xploit4